### ISSUE TITLE
Timeline / raphael fails in Firefox

### ISSUE THREAD

**Issue by jaylett** [historymesh/historymesh#19]
I'm running 6.0 (although I'm on the beta update channel), and get:

```
b[0] is undefined 
```

http://ubuntu:8000/static/js/raphael-min.js
 Line 7

Since we're running min in dev, I can't easily debug this :-/

**Comment by jaylett** [comment]
True in 7.0 as well.

**Comment by ashb** [comment]
That is usually a smyptom of trying to draw something with an invalid path or position.

Which page gave this error? Anything with a map?

**Comment by jaylett** [comment]
Think it was just the first page of automation, but I can't remember offhand.
